### PR TITLE
Add slicermorph

### PR DESCRIPTION
**Pull request by pieper**
@muratmaga this should be working.  The docker image builds for me but I didn't see a command line for how to test.

### CODE REVIEW

**Comment by muratmaga** [comment]
Thanks will try...

**Comment by pieper** [comment]
BTW, this should work once the /opt/slicer directory is made writable by the user. 

You can test mine with:

`docker run --rm -p 8080:8080 stevepieper/slicer-morph:4.11.20200930`

then go to `localhost:8080` in the browser.

**Comment by muratmaga** [comment]
Yep, I changed the opt/slicer mode to be 777. But going forward I see no reason installing there. I think it will simply go to the /home/docker.

**Comment by muratmaga** [comment]
Also, if you need to make changes or anything, the final version is in here: 
https://github.com/SlicerMorph/SlicerMorphCloud

**Comment by pieper** [comment]
Agreed, for the training use case it's better not to preinstall.  Still can be handy to have a 'batteries included' image ready to use for other purposes.  Anyway just wanted to close the loop on the topic.

**Pull request merged**
